name: ci-cd
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Obter código do projeto
        uses: actions/checkout@v4
      - name: setar ambiente dotnet
        uses: actions/setup-dotnet@v3.4.2
        with:
          dotnet-version: 8.x

      - name: Executar testes
        working-directory: ./02-review/src/Review-Filmes.Test.Unit
        run: dotnet test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          tags: |
            danilomarcus/review-jornada:v${{ github.run_number }}
            danilomarcus/review-jornada:latest
          context: ./02-review/src
          file: ./02-review/src/Review-Filmes.Web/Dockerfile
          push: true
      
  cd:
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: Obter código do projeto
        uses: actions/checkout@v4
      - name: preparar Kubeconfig
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}
      - name: Executar apply
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            ./02-review/k8s/deployment.yaml
          images: 'danilomarcus/review-jornada:v${{ github.run_number }}'